In [1]:
import numpy as np

In [ ]:
k = np.array([1,2,3])

In [ ]:
l = np.array([3,4,5])

In [ ]:
np.inner(k,l)

In [ ]:
np.linalg.norm(k,ord=1)

In [8]:
a = np.array([[3],[4]])
a **= 2

In [11]:
b = np.array([[3],[4]])

In [ ]:
np.linalg.norm(a) ** 2

In [ ]:
2 * np.identity(3)


In [ ]:
A_t = np.zeros((3,3))

In [ ]:
A_t[2][2] = 3
A_t

In [ ]:
a = np.ones((3, 1))
print(a.shape)
b = np.zeros((2, 1))
print(b.shape)

In [ ]:
c = np.r_[a,b]
c.shape

In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
x = x - np.mean(x, axis=0)
x

array([[-2.33333333, -7.        , -3.        ],
       [-3.33333333,  2.        ,  0.        ],
       [ 5.66666667,  5.        ,  3.        ]])

In [61]:
np.abs(x)

array([[1, 4, 3],
       [2, 5, 6],
       [7, 8, 9]])

In [7]:
A = np.random.random((3,3))
eigenValues, eigenVectors = np.linalg.eig(A)

In [8]:
eigenValues

array([-0.15211946,  1.23604844,  0.56559231])

In [9]:
idx = eigenValues.argsort()[::-1]   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]

In [10]:
eigenValues

array([ 1.23604844,  0.56559231, -0.15211946])

In [4]:
eigenVectors

array([[-0.49814536, -0.53335771, -0.88489979],
       [-0.63654616, -0.17773285,  0.25389007],
       [-0.58877855,  0.82700701,  0.39050249]])

In [50]:
np.sort(x.reshape(-1,1),axis = 0)[int(x.reshape(-1,1).shape[0] * 0.3)]

array([3])

In [49]:
w,v = np.linalg.eig(x)

In [30]:
w

array([ 1.61168440e+01, -1.11684397e+00, -8.58274334e-16])

In [32]:
v[:, 0:2]

array([[-0.23197069, -0.78583024],
       [-0.52532209, -0.08675134],
       [-0.8186735 ,  0.61232756]])

In [1]:
from numpy import source
import requests
import time
import matplotlib.pyplot as plt
from PIL import Image
import matplotlib.image as mpimg
url = 'http://buling.wudaoai.cn/retrieval'
while True :
    time.sleep(1)
    img = '2.jpg'
    files = {'local_img': open(img,'rb')}
    params = {'source' : 'album'}
    r = requests.post(url, files=files, params=params)
    print(r.json()['sentence'])
    Img = mpimg.imread(img)
    plt.imshow(Img)
    plt.axis('off')
    plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '2.jpg'